apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-08
  namespace: argocd
spec:
  generators:
  - git:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/best_practices/
        repoURL: https://github.com/Emmerson-Miranda/argocd.git
        revision: HEAD
        files:
        - path: "example-08/environment-config/**/config.yaml"
  template:
    metadata:
      name: '{{config.project}}-{{config.environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/{{config.repoURL}}
        targetRevision: '{{config.targetRevision}}'
        path: ./{{config.path}}
        helm:
          valueFiles:
          - https://raw.githubusercontent.com/Emmerson-Miranda/argocd/main/example-07/environment-config/{{config.environment}}/values.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{config.project}}-{{config.environment}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly={{config.syncPolicy.syncOptions.ApplyOutOfSyncOnly}}
          - PrunePropagationPolicy=foreground