kind: Secret
apiVersion: v1
metadata:
  name: vault-example
type: Opaque
data:
  usernameInline: PHBhdGg6a3YtdjIvZGF0YS9teS1zZWNyZXRzL3NlY3JldDEjdXNlcm5hbWU+
  passwordInline: PHBhdGg6a3YtdjIvZGF0YS9teS1zZWNyZXRzL3NlY3JldDEjcGFzc3dvcmQ+
  usernameValues: {{ .Values.usernameValues | b64enc }}
  passwordValues: {{ .Values.passwordValues | b64enc }}
