kind: Secret
apiVersion: v1
metadata:
  name: data-1-secret
type: Opaque
data:
  usernameInline: PHBhdGg6a3YtdjIvZGF0YS9teS1zZWNyZXRzL3NlY3JldDEjdXNlcm5hbWU+
  passwordInline: PHBhdGg6a3YtdjIvZGF0YS9teS1zZWNyZXRzL3NlY3JldDEjcGFzc3dvcmQ+

