kind: Secret
apiVersion: v1
metadata:
  name: string-1-secret
type: Opaque
stringData:
  usernameInline: <path:kv-v2/data/my-secrets/secret1#username>
  passwordInline: <path:kv-v2/data/my-secrets/secret1#password>

