kind: Secret
apiVersion: v1
metadata:
  name: my-secret-from-vault-string-example
type: Opaque
stringData:
  usernameInline: <path:kv-v2/data/my-secrets/secret1#username>
  passwordInline: <path:kv-v2/data/my-secrets/secret1#password>

