apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-02-prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 27.1.0
    helm:
      valueFiles:
      - $values/example-02/values/prometheus-values.yaml
  - repoURL: 'https://github.com/Emmerson-Miranda/argocd.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
