apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-02
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/example-02/values/prometheus-values.yaml
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: dev
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: example-02
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
