apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-01
  namespace: argocd
spec:
  project: myproject-01
  source:
    repoURL: https://github.com/Emmerson-Miranda/argocd.git
    targetRevision: HEAD
    path: example-01/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: example-01
