
## Additional labels to attach to all resources
commonMetaLabels: 
  argo-source: multisource-example

server:
  ## Prometheus server container name
  ##
  name: server

  ingress:
    ## If true, Prometheus server Ingress will be created
    ##
    enabled: true

    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx

    ## Redirect ingress to an additional defined port on the service
    # servicePort: 8081

    ## Prometheus server Ingress hostnames with optional path (passed through tpl)
    ## Must be provided if Ingress is enabled
    ##
    hosts: 
      - prometheus.owl.com

  ## hostAliases allows adding entries to /etc/hosts inside the containers
  hostAliases: 
    - ip: "127.0.0.1"
      hostnames:
        - "prometheus.owl.com"
