config:
  project: "example-06"
  repoURL: "https://github.com/Emmerson-Miranda/argocd.git"
  path: "example-06/helmchart"
  targetRevision: "HEAD"
  environment:
    name: "uat"
    replicas: 2
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"