

server:

  ingress:

    enabled: true

    hosts: 
      - prometheus.owl.com

  ## hostAliases allows adding entries to /etc/hosts inside the containers
  hostAliases: 
    - ip: "127.0.0.1"
      hostnames:
        - "prometheus.owl.com"
