server:

  ingress:
    enabled: true

    hosts: 
      - <path:kv-v2/data/my-secrets/prometheus#host>
      #- prometheus.owl.com

  ## hostAliases allows adding entries to /etc/hosts inside the containers
  hostAliases: 
    - ip: "127.0.0.1"
      hostnames:
        - <path:kv-v2/data/my-secrets/prometheus#host>
        #- prometheus.owl.com
