apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wiremock-matrix
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
                repoURL: https://github.com/Emmerson-Miranda/argocd.git
                revision: HEAD
                files:
                - path: "example-11/config/**/config.yaml"
                values: 
                  argoProject: '{{ .config.argoProject }}'
                  repoHelmURL: '{{ .config.repoHelmURL }}'
                  repoHelmTargetRevision: '{{ .config.repoHelmTargetRevision }}'
                  repoGitURL: '{{ .config.repoGitURL }}'
                  repoGitTargetRevision: '{{ .config.repoGitTargetRevision }}'
          - clusters: # Automatically use all clusters defined within Argo CD
              selector:
                matchLabels: # below condition avoid deploy apps in same cluster as argo (in-cluster)
                  type: applications # injected when we register the secret
  template:
    metadata:
      name: 'wiremock-matrix-{{.name}}' # 'name' field of the Secret
    spec:
      project: '{{ .values.argoProject }}'
      sources:
      - helm:
          valueFiles:
            - $values/{{.path.path}}/values.yaml # same folder as config.yaml loaded
        chart: wiremock
        repoURL: https://{{ .values.repoHelmURL }}
        targetRevision: '{{ .values.repoHelmTargetRevision }}'
      - repoURL: https://github.com/{{ .values.repoGitURL }}
        targetRevision: '{{ .values.repoGitTargetRevision }}'
        ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
