apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wiremock-matrix
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/Emmerson-Miranda/argocd.git
              revision: HEAD
              files:
              - path: "example-11/config/**/config.yaml"
              values: 
                componentName: '{{ .config.componentName }}'
                argoProject: '{{ .config.argoProject }}'
                repoHelmURL: '{{ .config.repoHelmURL }}'
                repoHelmChart: '{{ .config.repoHelmChart }}'
                repoHelmTargetRevision: '{{ .config.repoHelmTargetRevision }}'
                repoGitURL: '{{ .config.repoGitURL }}'
                repoGitTargetRevision: '{{ .config.repoGitTargetRevision }}'
                targetClusters: '{{ .config.environments }}'
            selector:
              matchExpressions:
                - {key: deploy, operator: In, values: ["true"]}
                #- {key: deploy, operator: Exists}
          # clusters generator, 'child' #2
          - clusters: # Automatically use all clusters defined within Argo CD
              selector:
                matchLabels: # below condition avoid deploy apps in same cluster as argo (in-cluster)
                  type: applications # injected when we register the secret
  template:
    metadata:
      name: 'matrix-{{.config.componentName}}-{{.name}}' # 'name' field of the Secret
      labels:
        pathDefaultValue: '{{default (index .path "0") "not-specified"}}' # https://masterminds.github.io/sprig/defaults.html
        path0: '{{index .path.segments 0}}' # https://github.com/argoproj/argo-cd/issues/12502
        path1: '{{index .path.segments 1}}' 
        path2: '{{index .path.segments 2}}' 
        filename: '{{.path.filenameNormalized}}'
        envs: '{{.config.environments | join "_"}}'
    spec:
      project: '{{ .values.argoProject }}'
      sources:
      - helm:
          valueFiles:
            - $values/{{.path.path}}/values.yaml # same folder as config.yaml loaded
        chart: '{{ .values.repoHelmChart }}'
        repoURL: '{{ .values.repoHelmURL }}'
        targetRevision: '{{ .values.repoHelmTargetRevision }}'
      - repoURL: https://github.com/{{ .values.repoGitURL }}
        targetRevision: '{{ .values.repoGitTargetRevision }}'
        ref: values
      destination:
        #server: '{{.server}}'
        name: '{{.name}}' # using argocd cluster name instead of server address
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
