config:
  project: "example-09"
  repoGitURL: "Emmerson-Miranda/argocd.git"
  repoHelmURL: "charts.deliveryhero.io/"
  path: "example-09/helmchart"
  targetRevision: "HEAD"
  environment: "dev"
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"