---
# https://github.com/argoproj/argo-events/blob/master/examples/event-sources/resource.yaml
# https://github.com/argoproj/argo-events/blob/master/examples/sensors/resource.yaml

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: cluster-deleted-in-argocd
  namespace: argo-events
spec:
  template:
    serviceAccountName: argoworkflow-executor # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
  resource:
    deleted-argocd-secret:
      # namespace to listen events within
      namespace: argocd
      # resource group
      group: ""
      # resource version
      version: v1
      # resource kind
      resource: secrets
      # type of events
      # possible values are ADD, DELETE, UPDATE
      # Optional
      eventTypes:
        - DELETE
        - UPDATE
      filter:
        # This indicates only watch the events happened after the service start time.
        afterStart: true
        # labels and filters are meant to provide K8s API options to filter the object list that are being watched.
        # Please read https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api for more details.

        # labels provide listing options to K8s API to watch objects
        labels:
          - key: argocd.argoproj.io/secret-type
            # Supported operations like ==, !=, etc.
            # Defaults to ==.
            # Refer https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors for more info.
            # optional.
            operation: "=="
            value: cluster

---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: trigger-delete-cluster-workflow
  namespace: argo-events
spec:
  template:
    serviceAccountName: argoworkflow-executor
  dependencies:
    - name: cluster-deleted
      eventSourceName: cluster-deleted-in-argocd
      eventName: deleted-argocd-secret
  triggers:
    - template:
        name: argocd-apps-cleanup-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cleanup-cluster-task-
                labels:
                  app: cleanup-cluster-task
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by the event payload from cluster-deleted
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: cluster-deleted
                # https://argoproj.github.io/argo-events/eventsources/setup/resource/#event-structure
                #dataKey: body
                #dataKey: resource # value: secrets
                #dataKey: body.metadata.name  # value: mycluster-secret
                dataKey: body.metadata.labels.cluster
              dest: spec.arguments.parameters.0.value
      retryStrategy:
        steps: 3
