---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: cluster-deleted-in-argocd
  namespace: argo-events
spec:
  template:
    serviceAccountName: argoworkflow-executor # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
  resource:
    deleted-argocd-secret:
      # namespace to listen events within
      namespace: argocd
      # resource group
      group: ""
      # resource version
      version: v1
      # resource kind
      resource: secrets
      # type of events
      # possible values are ADD, DELETE, UPDATE
      # Optional
      eventTypes:
        - DELETE

---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: trigger-delete-cluster-workflow
  namespace: argo-events
spec:
  template:
    serviceAccountName: argoworkflow-executor
  dependencies:
    - name: cluster-deleted
      eventSourceName: cluster-deleted-in-argocd
      eventName: deleted-argocd-secret
  triggers:
    - template:
        name: argocd-apps-cleanup-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cleanup-cluster-task-
                labels:
                  app: cleanup-cluster-task
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by the event payload from test-dep
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
      retryStrategy:
        steps: 3
