apiVersion: v1
kind: Secret
metadata:
  name: "PLACEHOLDER_CLUSTER-secret"
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster: "PLACEHOLDER_CLUSTER"
type: Opaque
stringData:
  name: "PLACEHOLDER_CLUSTER"
  server: https://192.168.64.1:8443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "certData": "PLACEHOLDER_CERT_DATA",
        "keyData": "PLACEHOLDER_KEY_DATA",
        "caData": "PLACEHOLDER_CA_DATA"
      }
    }
