apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-09
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: deliveryhero
      targetRevision: 1.4.1
      helm:
        valueFiles:
          - ./example-09/environment-config/dev/values.yaml
      chart: wiremock
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: example-09