{{- range $.Values.servers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "example.name" . }}
  labels:
    app: {{ template "example.name" . }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    environment: {{ $.Values.environment.name | squote}}
    project: {{ $.Values.project | squote}}
    #configuration.path: {{ printf "%s" $.Values.configuration.path}}
    configuration.basename: {{ $.Values.configuration.basename | squote}}
spec:
  replicas: {{ $.Values.environment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "example.name" . }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "example.name" . }}
        release: {{ $.Release.Name }}
        environment: {{ $.Values.environment.name }}
    spec:
      containers:
        - name: {{ template "example.name" . }}
          image: "{{ .image }}:{{ .tag }}"
          imagePullPolicy: {{ $.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .containerPort }}
              protocol: TCP
          env:
          - name: ENVIRONMENT
            value: {{ $.Values.environment.name }}

{{- end }} 