apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-07
  namespace: argocd
spec:
  generators:
  - git:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/best_practices/
        repoURL: https://github.com/Emmerson-Miranda/argocd.git
        revision: HEAD
        files:
        - path: "example-07/environment-config/**/config.yaml"
  template:
    metadata:
      name: '{{config.project}}-{{config.environment.name}}'
    spec:
      project: default
      sources:
      - repoURL: https://github.com/{{config.repoURL}}
        targetRevision: '{{config.targetRevision}}'
        path: ./{{config.path}}
        helm:
          valueFiles:
          - $values/{{config.project}}/environment-config/{{config.environment.name}}/values.yaml
      - repoURL: https://github.com/{{config.repoURL}}
        targetRevision: '{{config.targetRevision}}'
        ref: values
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{config.project}}-{{config.environment.name}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly={{config.syncPolicy.syncOptions.ApplyOutOfSyncOnly}}
          - PrunePropagationPolicy=foreground