apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-15
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Emmerson-Miranda/argocd.git
    targetRevision: HEAD
    path: example-15/helmchart
    helm:
      valueFiles:
        - /example-15/values/my-helmchart-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: helmchart
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground