---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-argocd-secrets
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argoworkflow-executor-read-secrets
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argoworkflow-executor
    namespace: argo-events
roleRef:
  kind: Role
  name: read-argocd-secrets
  apiGroup: rbac.authorization.k8s.io