config:
  project: "example-09"
  repoURL: "Emmerson-Miranda/argocd.git"
  path: "example-09/helmchart"
  targetRevision: "HEAD"
  environment: "uat"
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"