apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-18
  namespace: argocd
  labels:
    cluster: application-cluster
spec:
  project: my-project
  source:
    repoURL: https://github.com/Emmerson-Miranda/argocd.git
    targetRevision: HEAD
    path: example-18/manifests/applications
  destination:
    server: https://192.168.64.1:8443
    namespace: example-18
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground