apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifests
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: manifests
    server: 'https://kubernetes.default.svc'
  source:
    path: example-13/manifests
    repoURL: 'https://github.com/Emmerson-Miranda/argocd.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground