kind: Secret
apiVersion: v1
metadata:
  name: vault-example
type: Opaque
data:
  username: PHBhdGg6a3YtdjIvZGF0YS9teS1zZWNyZXRzL3NlY3JldDEjdXNlcm5hbWU+
  password: PHBhdGg6a3YtdjIvZGF0YS9teS1zZWNyZXRzL3NlY3JldDEjcGFzc3dvcmQ+