kind: Secret
apiVersion: v1
metadata:
  name: vault-example
type: Opaque
data:
  username-inline: PHBhdGg6a3YtdjIvZGF0YS9teS1zZWNyZXRzL3NlY3JldDEjdXNlcm5hbWU+
  password-inline: PHBhdGg6a3YtdjIvZGF0YS9teS1zZWNyZXRzL3NlY3JldDEjcGFzc3dvcmQ+
  username-values: {{ .Values.username-values | b64enc}}
  password-values: {{ .Values.password-values | b64enc}}
