apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: 'default'
  sources:
  - helm:
    chart: 'rabbitmq' # https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '13.0.2'
  destination:
    name: 'in-cluster'
    namespace: 'rabbitmq'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
