apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  project: 'default'
  sources:
  - helm:
    chart: 'cert-manager' # https://github.com/bitnami/charts/tree/main/bitnami/cert-manager
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '1.0.0'
  destination:
    name: 'in-cluster'
    namespace: 'cert-manager'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
