apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-my-helmchart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  finalizers:
      # The default behaviour is foreground cascading deletion
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Emmerson-Miranda/argocd.git
    targetRevision: HEAD
    path: example-14/helmchart
  destination:
    server: "https://kubernetes.default.svc"
    namespace: my-helmchart
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true