apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helmchart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  source:
    repoURL: https://github.com/Emmerson-Miranda/argocd.git
    targetRevision: HEAD
    path: example-14/helmchart
  destination:
    server: "https://kubernetes.default.svc"
    namespace: my-helmchart
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground