deploy: "true"
config:
  componentName: "prometheus"
  argoProject: "default"
  repoGitURL: "Emmerson-Miranda/argocd.git"
  repoGitTargetRevision: "HEAD"
  # https://artifacthub.io/packages/helm/prometheus-community/prometheus
  repoHelmURL: "https://prometheus-community.github.io/helm-charts/"
  repoHelmChart: "prometheus-community/prometheus"
  repoHelmTargetRevision: "25.16.0"
  environments: 
  - "ci"
  - "uat"
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"