deploy: "true"
config:
  componentName: "prometheus"
  argoProject: "default"
  repoGitURL: "Emmerson-Miranda/argocd.git"
  repoGitTargetRevision: "HEAD"
  #  helm pull --destination /tmp/deleteme --version 25.16.0 --repo https://prometheus-community.github.io/helm-charts prometheus
  # https://artifacthub.io/packages/helm/prometheus-community/prometheus
  repoHelmURL: "https://prometheus-community.github.io/helm-charts"
  repoHelmChart: "kube-prometheus-stack"
  repoHelmTargetRevision: "13.7.2"
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"