deploy: "false"
config:
  componentName: "prometheus"
  argoProject: "default"
  repoGitURL: "Emmerson-Miranda/argocd.git"
  repoGitTargetRevision: "HEAD"
  # https://artifacthub.io/packages/helm/prometheus-community/prometheus
  repoHelmURL: "https://prometheus-community.github.io/helm-charts/prometheus-community/"
  repoHelmChart: "prometheus"
  repoHelmTargetRevision: "25.16.0"
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"