config:
  argoProject: "default"
  repoGitURL: "Emmerson-Miranda/argocd.git"
  repoGitTargetRevision: "HEAD"
  repoHelmURL: "charts.deliveryhero.io/"
  repoHelmTargetRevision: "1.4.1"
  environments: 
  - "ci"
  - "uat"
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"