deploy: "true"
environments: 
  - "ci"
  - "uat"
environmentsv2: 
  ci: "true"
  uat": "true"
config:
  componentName: "wiremock"
  argoProject: "default"
  repoGitURL: "Emmerson-Miranda/argocd.git"
  repoGitTargetRevision: "HEAD"
  # https://artifacthub.io/packages/helm/deliveryhero/wiremock
  repoHelmURL: "https://charts.deliveryhero.io/"
  repoHelmChart: "wiremock"
  repoHelmTargetRevision: "1.4.1"
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"