servers:
  - name: upstream-example-03-01
    image: emmerson/upstream
    tag: mockv2
    pullPolicy: IfNotPresent
    containerPort: 10003
  - name: upstream-example-03-02
    replicas: 2
    image: emmerson/upstream
    tag: mockv2
    pullPolicy: IfNotPresent
    containerPort: 10003
  - name: upstream-example-03-03
    replicas: 1
    image: emmerson/upstream
    tag: mockv2
    pullPolicy: IfNotPresent
    containerPort: 10003
