config:
  project: "example-08"
  repoURL: "Emmerson-Miranda/argocd.git"
  path: "example-08/helmchart"
  targetRevision: "HEAD"
  environment: "dev"
  syncPolicy:
    syncOptions:
      ApplyOutOfSyncOnly: "true"